### ISSUE TITLE
Switch to airbnb JS code style

### ISSUE THREAD

**Issue by tomek-he-him** [tomekwi/mithril-n#12]
In response to #11.

More reading: https://github.com/feross/standard

**Comment by barneycarroll** [comment]
Related: heard that [AirBnB's Javascript Style](https://github.com/airbnb/javascript/blob/master/README.md) was the first one reader had seen that didn't include any bullshit opinions. Could be worth a look. They also have a Gitter to bikeshed over the specifics... Looks good to me!

**Comment by tomekwi** [comment]
Hey, thanks for the link – appeals to me :) More than standard JS. Is there any tool like http://npm.im/standard for that?

**Comment by barneycarroll** [comment]
They've got a couple of definitions for linters: https://github.com/airbnb/javascript/blob/master/README.md#resources

An eslint PR would be nice.

**Comment by tomekwi** [comment]
I find the AirBnB guide a lot more comprehensive and down-to-business.

What I like about standard is simplicity (no config) and… branding. Yes, I do buy stuff for their looks :) But I guess so do many developers. Just as a good readme with a green travis badge looks reassuring, so does a well-known logo.

Neither of the styles exactly matches my personal taste. AirBnB is better and has good recognition. It'd be great if it had better branding as well. I guess I'll suggest that to them and pick AirBnB after all.

**Comment by tomekwi** [comment]
For reference: https://github.com/airbnb/javascript/issues/263

**Comment by tomekwi** [comment]
All in all I think the code has become less pretty and readable. But it's just my opinion.

And it's good tradeoff – as the lib should now be more friendly for other contributors :)
