### ISSUE TITLE
Automate compilation to ES5

### ISSUE THREAD

**Issue by barneycarroll** [tomekwi/mithril-n#2]

**Comment by tomekwi** [comment]
#9 is ready. It did take a good while – as I couldn't find a reasonable formatter for a universal ES5 distribution, I decided to code it myself. [6-to-library](https://github.com/tomekwi/6-to-library.js).

To build, run `gulp`. That's yet to be automated on `npm publish`, perhaps even over Travis.

Let me know if you have any issues.

**Comment by barneycarroll** [comment]
Shiny! Will check it out in the morning…

**Comment by barneycarroll** [comment]
So the compiled ES5 code is broken in several ways. For a start this variation on UMD has [this weird expression for checking for `module` implementation](https://gist.github.com/barneycarroll/3a1b6e913d71004a4034/56cb8da9083fa331d6c49a932c8b4a24b530a776#file-n-js-L6):

```javascript
module && typeof module.exports !== "undefined"
```

I don't understand why it could be considered important to do a specific undefined check on `module.exports` but not on `module`. As it turns out, this breaks outside of Node because `module` is undefined.

There's also a weird bug I can't quite seem to isolate in the compiled code proper whereby at some point an Array is invoked as a function.

**Comment by tomekwi** [comment]
Sorry for that, my bad. I've fixed it – now it works with me.

> I don't understand why it could be considered important to do a specific undefined check on module.exports but not on module.

I'm used to doing this when I have to access a property of an object, but I'm not sure the variable really is an object:
```
function (args) {
  if (args && args.doSomething) ...
  }
```

Somehow I overlooked that `module` throws a ReferenceError instead of evaluting to `undefined`.

**Comment by tomekwi** [comment]
By the way, it turned out that the core 6to5 team was working on the same things in parallel. They ended up with a better solution, far deeper integrated.

They don't support globals just yet, but that's also on the roadmap. Until then I think we'll stick with what we have. When globals land in 6to5, we can get rid of my formatter (which I've already deprecated).

**Comment by tomekwi** [comment]
> There's also a weird bug I can't quite seem to isolate in the compiled code proper whereby at some point an Array is invoked as a function.

Perhaps you're talking about this: [:45](https://gist.github.com/barneycarroll/3a1b6e913d71004a4034/56cb8da9083fa331d6c49a932c8b4a24b530a776#file-n-js-L45)? Seems more or less OK to me. What looks alarming is this: [:25](https://gist.github.com/barneycarroll/3a1b6e913d71004a4034/56cb8da9083fa331d6c49a932c8b4a24b530a776#file-n-js-L25) – there's no such thing as `Array.from` in ES5.

I'll need to investigate a little further when I have some time. It's a tight time for me now, but I'll try to push the thing forward next week.

**Comment by tomekwi** [comment]
@barneycarroll so this is the problem: https://6to5.org/docs/caveats/#polyfills . If we want to use array destructuring, we need a polyfill for that. I'd rather get rid of it, and avoid the polyfill.

If you experience any more problems with the ES5 version, drop another line here.
